// Code generated by go-swagger; DO NOT EDIT.

package node_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v5/models"
)

// GetByUUIDReader is a Reader for the GetByUUID structure.
type GetByUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetByUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetByUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetByUUIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetByUUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetByUUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetByUUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /node/u/{Uuid}] GetByUuid", response, response.Code())
	}
}

// NewGetByUUIDOK creates a GetByUUIDOK with default headers values
func NewGetByUUIDOK() *GetByUUIDOK {
	return &GetByUUIDOK{}
}

/*
GetByUUIDOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetByUUIDOK struct {
	Payload *models.RestNode
}

// IsSuccess returns true when this get by Uuid o k response has a 2xx status code
func (o *GetByUUIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get by Uuid o k response has a 3xx status code
func (o *GetByUUIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get by Uuid o k response has a 4xx status code
func (o *GetByUUIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get by Uuid o k response has a 5xx status code
func (o *GetByUUIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get by Uuid o k response a status code equal to that given
func (o *GetByUUIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get by Uuid o k response
func (o *GetByUUIDOK) Code() int {
	return 200
}

func (o *GetByUUIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidOK %s", 200, payload)
}

func (o *GetByUUIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidOK %s", 200, payload)
}

func (o *GetByUUIDOK) GetPayload() *models.RestNode {
	return o.Payload
}

func (o *GetByUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestNode)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByUUIDUnauthorized creates a GetByUUIDUnauthorized with default headers values
func NewGetByUUIDUnauthorized() *GetByUUIDUnauthorized {
	return &GetByUUIDUnauthorized{}
}

/*
GetByUUIDUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type GetByUUIDUnauthorized struct {
	Payload *models.RestError
}

// IsSuccess returns true when this get by Uuid unauthorized response has a 2xx status code
func (o *GetByUUIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get by Uuid unauthorized response has a 3xx status code
func (o *GetByUUIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get by Uuid unauthorized response has a 4xx status code
func (o *GetByUUIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get by Uuid unauthorized response has a 5xx status code
func (o *GetByUUIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get by Uuid unauthorized response a status code equal to that given
func (o *GetByUUIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get by Uuid unauthorized response
func (o *GetByUUIDUnauthorized) Code() int {
	return 401
}

func (o *GetByUUIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidUnauthorized %s", 401, payload)
}

func (o *GetByUUIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidUnauthorized %s", 401, payload)
}

func (o *GetByUUIDUnauthorized) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GetByUUIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByUUIDForbidden creates a GetByUUIDForbidden with default headers values
func NewGetByUUIDForbidden() *GetByUUIDForbidden {
	return &GetByUUIDForbidden{}
}

/*
GetByUUIDForbidden describes a response with status code 403, with default header values.

User has no permission to access this particular resource
*/
type GetByUUIDForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this get by Uuid forbidden response has a 2xx status code
func (o *GetByUUIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get by Uuid forbidden response has a 3xx status code
func (o *GetByUUIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get by Uuid forbidden response has a 4xx status code
func (o *GetByUUIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get by Uuid forbidden response has a 5xx status code
func (o *GetByUUIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get by Uuid forbidden response a status code equal to that given
func (o *GetByUUIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get by Uuid forbidden response
func (o *GetByUUIDForbidden) Code() int {
	return 403
}

func (o *GetByUUIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidForbidden %s", 403, payload)
}

func (o *GetByUUIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidForbidden %s", 403, payload)
}

func (o *GetByUUIDForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GetByUUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByUUIDNotFound creates a GetByUUIDNotFound with default headers values
func NewGetByUUIDNotFound() *GetByUUIDNotFound {
	return &GetByUUIDNotFound{}
}

/*
GetByUUIDNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type GetByUUIDNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this get by Uuid not found response has a 2xx status code
func (o *GetByUUIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get by Uuid not found response has a 3xx status code
func (o *GetByUUIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get by Uuid not found response has a 4xx status code
func (o *GetByUUIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get by Uuid not found response has a 5xx status code
func (o *GetByUUIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get by Uuid not found response a status code equal to that given
func (o *GetByUUIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get by Uuid not found response
func (o *GetByUUIDNotFound) Code() int {
	return 404
}

func (o *GetByUUIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidNotFound %s", 404, payload)
}

func (o *GetByUUIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidNotFound %s", 404, payload)
}

func (o *GetByUUIDNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GetByUUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByUUIDInternalServerError creates a GetByUUIDInternalServerError with default headers values
func NewGetByUUIDInternalServerError() *GetByUUIDInternalServerError {
	return &GetByUUIDInternalServerError{}
}

/*
GetByUUIDInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type GetByUUIDInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this get by Uuid internal server error response has a 2xx status code
func (o *GetByUUIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get by Uuid internal server error response has a 3xx status code
func (o *GetByUUIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get by Uuid internal server error response has a 4xx status code
func (o *GetByUUIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get by Uuid internal server error response has a 5xx status code
func (o *GetByUUIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get by Uuid internal server error response a status code equal to that given
func (o *GetByUUIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get by Uuid internal server error response
func (o *GetByUUIDInternalServerError) Code() int {
	return 500
}

func (o *GetByUUIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidInternalServerError %s", 500, payload)
}

func (o *GetByUUIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /node/u/{Uuid}][%d] getByUuidInternalServerError %s", 500, payload)
}

func (o *GetByUUIDInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GetByUUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
