// Code generated by go-swagger; DO NOT EDIT.

package token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResetPasswordTokenParams creates a new ResetPasswordTokenParams object
// with the default values initialized.
func NewResetPasswordTokenParams() *ResetPasswordTokenParams {
	var ()
	return &ResetPasswordTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResetPasswordTokenParamsWithTimeout creates a new ResetPasswordTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResetPasswordTokenParamsWithTimeout(timeout time.Duration) *ResetPasswordTokenParams {
	var ()
	return &ResetPasswordTokenParams{

		timeout: timeout,
	}
}

// NewResetPasswordTokenParamsWithContext creates a new ResetPasswordTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewResetPasswordTokenParamsWithContext(ctx context.Context) *ResetPasswordTokenParams {
	var ()
	return &ResetPasswordTokenParams{

		Context: ctx,
	}
}

// NewResetPasswordTokenParamsWithHTTPClient creates a new ResetPasswordTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResetPasswordTokenParamsWithHTTPClient(client *http.Client) *ResetPasswordTokenParams {
	var ()
	return &ResetPasswordTokenParams{
		HTTPClient: client,
	}
}

/*ResetPasswordTokenParams contains all the parameters to send to the API endpoint
for the reset password token operation typically these are written to a http.Request
*/
type ResetPasswordTokenParams struct {

	/*UserLogin*/
	UserLogin string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reset password token params
func (o *ResetPasswordTokenParams) WithTimeout(timeout time.Duration) *ResetPasswordTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset password token params
func (o *ResetPasswordTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset password token params
func (o *ResetPasswordTokenParams) WithContext(ctx context.Context) *ResetPasswordTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset password token params
func (o *ResetPasswordTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset password token params
func (o *ResetPasswordTokenParams) WithHTTPClient(client *http.Client) *ResetPasswordTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset password token params
func (o *ResetPasswordTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserLogin adds the userLogin to the reset password token params
func (o *ResetPasswordTokenParams) WithUserLogin(userLogin string) *ResetPasswordTokenParams {
	o.SetUserLogin(userLogin)
	return o
}

// SetUserLogin adds the userLogin to the reset password token params
func (o *ResetPasswordTokenParams) SetUserLogin(userLogin string) {
	o.UserLogin = userLogin
}

// WriteToRequest writes these params to a swagger request
func (o *ResetPasswordTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param UserLogin
	if err := r.SetPathParam("UserLogin", o.UserLogin); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
