// Code generated by go-swagger; DO NOT EDIT.

package health_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	models2 "github.com/pydio/cells-sdk-go/v5/apiv1/models"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// APILiveReader is a Reader for the APILive structure.
type APILiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APILiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPILiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAPILiveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAPILiveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAPILiveNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAPILiveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /health/live] ApiLive", response, response.Code())
	}
}

// NewAPILiveOK creates a APILiveOK with default headers values
func NewAPILiveOK() *APILiveOK {
	return &APILiveOK{}
}

/*
APILiveOK describes a response with status code 200, with default header values.

A successful response.
*/
type APILiveOK struct {
	Payload *models2.RestHealthServiceResponse
}

// IsSuccess returns true when this api live o k response has a 2xx status code
func (o *APILiveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api live o k response has a 3xx status code
func (o *APILiveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api live o k response has a 4xx status code
func (o *APILiveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api live o k response has a 5xx status code
func (o *APILiveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api live o k response a status code equal to that given
func (o *APILiveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api live o k response
func (o *APILiveOK) Code() int {
	return 200
}

func (o *APILiveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveOK %s", 200, payload)
}

func (o *APILiveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveOK %s", 200, payload)
}

func (o *APILiveOK) GetPayload() *models2.RestHealthServiceResponse {
	return o.Payload
}

func (o *APILiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestHealthServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPILiveUnauthorized creates a APILiveUnauthorized with default headers values
func NewAPILiveUnauthorized() *APILiveUnauthorized {
	return &APILiveUnauthorized{}
}

/*
APILiveUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type APILiveUnauthorized struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this api live unauthorized response has a 2xx status code
func (o *APILiveUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api live unauthorized response has a 3xx status code
func (o *APILiveUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api live unauthorized response has a 4xx status code
func (o *APILiveUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this api live unauthorized response has a 5xx status code
func (o *APILiveUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this api live unauthorized response a status code equal to that given
func (o *APILiveUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the api live unauthorized response
func (o *APILiveUnauthorized) Code() int {
	return 401
}

func (o *APILiveUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveUnauthorized %s", 401, payload)
}

func (o *APILiveUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveUnauthorized %s", 401, payload)
}

func (o *APILiveUnauthorized) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *APILiveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPILiveForbidden creates a APILiveForbidden with default headers values
func NewAPILiveForbidden() *APILiveForbidden {
	return &APILiveForbidden{}
}

/*
APILiveForbidden describes a response with status code 403, with default header values.

User has no permission to access this particular resource
*/
type APILiveForbidden struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this api live forbidden response has a 2xx status code
func (o *APILiveForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api live forbidden response has a 3xx status code
func (o *APILiveForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api live forbidden response has a 4xx status code
func (o *APILiveForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this api live forbidden response has a 5xx status code
func (o *APILiveForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this api live forbidden response a status code equal to that given
func (o *APILiveForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the api live forbidden response
func (o *APILiveForbidden) Code() int {
	return 403
}

func (o *APILiveForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveForbidden %s", 403, payload)
}

func (o *APILiveForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveForbidden %s", 403, payload)
}

func (o *APILiveForbidden) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *APILiveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPILiveNotFound creates a APILiveNotFound with default headers values
func NewAPILiveNotFound() *APILiveNotFound {
	return &APILiveNotFound{}
}

/*
APILiveNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type APILiveNotFound struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this api live not found response has a 2xx status code
func (o *APILiveNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api live not found response has a 3xx status code
func (o *APILiveNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api live not found response has a 4xx status code
func (o *APILiveNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this api live not found response has a 5xx status code
func (o *APILiveNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this api live not found response a status code equal to that given
func (o *APILiveNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the api live not found response
func (o *APILiveNotFound) Code() int {
	return 404
}

func (o *APILiveNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveNotFound %s", 404, payload)
}

func (o *APILiveNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveNotFound %s", 404, payload)
}

func (o *APILiveNotFound) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *APILiveNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPILiveInternalServerError creates a APILiveInternalServerError with default headers values
func NewAPILiveInternalServerError() *APILiveInternalServerError {
	return &APILiveInternalServerError{}
}

/*
APILiveInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type APILiveInternalServerError struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this api live internal server error response has a 2xx status code
func (o *APILiveInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api live internal server error response has a 3xx status code
func (o *APILiveInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api live internal server error response has a 4xx status code
func (o *APILiveInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this api live internal server error response has a 5xx status code
func (o *APILiveInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this api live internal server error response a status code equal to that given
func (o *APILiveInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the api live internal server error response
func (o *APILiveInternalServerError) Code() int {
	return 500
}

func (o *APILiveInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveInternalServerError %s", 500, payload)
}

func (o *APILiveInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/live][%d] apiLiveInternalServerError %s", 500, payload)
}

func (o *APILiveInternalServerError) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *APILiveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
