// Code generated by go-swagger; DO NOT EDIT.

package health_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServiceReadyParams creates a new ServiceReadyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServiceReadyParams() *ServiceReadyParams {
	return &ServiceReadyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServiceReadyParamsWithTimeout creates a new ServiceReadyParams object
// with the ability to set a timeout on a request.
func NewServiceReadyParamsWithTimeout(timeout time.Duration) *ServiceReadyParams {
	return &ServiceReadyParams{
		timeout: timeout,
	}
}

// NewServiceReadyParamsWithContext creates a new ServiceReadyParams object
// with the ability to set a context for a request.
func NewServiceReadyParamsWithContext(ctx context.Context) *ServiceReadyParams {
	return &ServiceReadyParams{
		Context: ctx,
	}
}

// NewServiceReadyParamsWithHTTPClient creates a new ServiceReadyParams object
// with the ability to set a custom HTTPClient for a request.
func NewServiceReadyParamsWithHTTPClient(client *http.Client) *ServiceReadyParams {
	return &ServiceReadyParams{
		HTTPClient: client,
	}
}

/*
ServiceReadyParams contains all the parameters to send to the API endpoint

	for the service ready operation.

	Typically these are written to a http.Request.
*/
type ServiceReadyParams struct {

	// ServiceName.
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the service ready params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceReadyParams) WithDefaults() *ServiceReadyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the service ready params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceReadyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the service ready params
func (o *ServiceReadyParams) WithTimeout(timeout time.Duration) *ServiceReadyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service ready params
func (o *ServiceReadyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service ready params
func (o *ServiceReadyParams) WithContext(ctx context.Context) *ServiceReadyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service ready params
func (o *ServiceReadyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service ready params
func (o *ServiceReadyParams) WithHTTPClient(client *http.Client) *ServiceReadyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service ready params
func (o *ServiceReadyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceName adds the serviceName to the service ready params
func (o *ServiceReadyParams) WithServiceName(serviceName string) *ServiceReadyParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the service ready params
func (o *ServiceReadyParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceReadyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ServiceName
	if err := r.SetPathParam("ServiceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
