// Code generated by go-swagger; DO NOT EDIT.

package node_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"github.com/pydio/cells-sdk-go/v5/apiv2/models"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePublicLinkParams creates a new CreatePublicLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePublicLinkParams() *CreatePublicLinkParams {
	return &CreatePublicLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePublicLinkParamsWithTimeout creates a new CreatePublicLinkParams object
// with the ability to set a timeout on a request.
func NewCreatePublicLinkParamsWithTimeout(timeout time.Duration) *CreatePublicLinkParams {
	return &CreatePublicLinkParams{
		timeout: timeout,
	}
}

// NewCreatePublicLinkParamsWithContext creates a new CreatePublicLinkParams object
// with the ability to set a context for a request.
func NewCreatePublicLinkParamsWithContext(ctx context.Context) *CreatePublicLinkParams {
	return &CreatePublicLinkParams{
		Context: ctx,
	}
}

// NewCreatePublicLinkParamsWithHTTPClient creates a new CreatePublicLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePublicLinkParamsWithHTTPClient(client *http.Client) *CreatePublicLinkParams {
	return &CreatePublicLinkParams{
		HTTPClient: client,
	}
}

/*
CreatePublicLinkParams contains all the parameters to send to the API endpoint

	for the create public link operation.

	Typically these are written to a http.Request.
*/
type CreatePublicLinkParams struct {

	// PublicLinkRequest.
	PublicLinkRequest *models.RestPublicLinkRequest

	// UUID.
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create public link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePublicLinkParams) WithDefaults() *CreatePublicLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create public link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePublicLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create public link params
func (o *CreatePublicLinkParams) WithTimeout(timeout time.Duration) *CreatePublicLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create public link params
func (o *CreatePublicLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create public link params
func (o *CreatePublicLinkParams) WithContext(ctx context.Context) *CreatePublicLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create public link params
func (o *CreatePublicLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create public link params
func (o *CreatePublicLinkParams) WithHTTPClient(client *http.Client) *CreatePublicLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create public link params
func (o *CreatePublicLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPublicLinkRequest adds the publicLinkRequest to the create public link params
func (o *CreatePublicLinkParams) WithPublicLinkRequest(publicLinkRequest *models.RestPublicLinkRequest) *CreatePublicLinkParams {
	o.SetPublicLinkRequest(publicLinkRequest)
	return o
}

// SetPublicLinkRequest adds the publicLinkRequest to the create public link params
func (o *CreatePublicLinkParams) SetPublicLinkRequest(publicLinkRequest *models.RestPublicLinkRequest) {
	o.PublicLinkRequest = publicLinkRequest
}

// WithUUID adds the uuid to the create public link params
func (o *CreatePublicLinkParams) WithUUID(uuid string) *CreatePublicLinkParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the create public link params
func (o *CreatePublicLinkParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePublicLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PublicLinkRequest != nil {
		if err := r.SetBodyParam(o.PublicLinkRequest); err != nil {
			return err
		}
	}

	// path param Uuid
	if err := r.SetPathParam("Uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
