// Code generated by go-swagger; DO NOT EDIT.

package node_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v5/apiv2/models"
)

// CreateReader is a Reader for the Create structure.
type CreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /n/nodes/create] Create", response, response.Code())
	}
}

// NewCreateOK creates a CreateOK with default headers values
func NewCreateOK() *CreateOK {
	return &CreateOK{}
}

/*
CreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateOK struct {
	Payload *models.RestNodeCollection
}

// IsSuccess returns true when this create o k response has a 2xx status code
func (o *CreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create o k response has a 3xx status code
func (o *CreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create o k response has a 4xx status code
func (o *CreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create o k response has a 5xx status code
func (o *CreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create o k response a status code equal to that given
func (o *CreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create o k response
func (o *CreateOK) Code() int {
	return 200
}

func (o *CreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createOK %s", 200, payload)
}

func (o *CreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createOK %s", 200, payload)
}

func (o *CreateOK) GetPayload() *models.RestNodeCollection {
	return o.Payload
}

func (o *CreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestNodeCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUnauthorized creates a CreateUnauthorized with default headers values
func NewCreateUnauthorized() *CreateUnauthorized {
	return &CreateUnauthorized{}
}

/*
CreateUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type CreateUnauthorized struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create unauthorized response has a 2xx status code
func (o *CreateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create unauthorized response has a 3xx status code
func (o *CreateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create unauthorized response has a 4xx status code
func (o *CreateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create unauthorized response has a 5xx status code
func (o *CreateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create unauthorized response a status code equal to that given
func (o *CreateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create unauthorized response
func (o *CreateUnauthorized) Code() int {
	return 401
}

func (o *CreateUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createUnauthorized %s", 401, payload)
}

func (o *CreateUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createUnauthorized %s", 401, payload)
}

func (o *CreateUnauthorized) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateForbidden creates a CreateForbidden with default headers values
func NewCreateForbidden() *CreateForbidden {
	return &CreateForbidden{}
}

/*
CreateForbidden describes a response with status code 403, with default header values.

User has no permission to access this particular resource
*/
type CreateForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create forbidden response has a 2xx status code
func (o *CreateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create forbidden response has a 3xx status code
func (o *CreateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create forbidden response has a 4xx status code
func (o *CreateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create forbidden response has a 5xx status code
func (o *CreateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create forbidden response a status code equal to that given
func (o *CreateForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create forbidden response
func (o *CreateForbidden) Code() int {
	return 403
}

func (o *CreateForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createForbidden %s", 403, payload)
}

func (o *CreateForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createForbidden %s", 403, payload)
}

func (o *CreateForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNotFound creates a CreateNotFound with default headers values
func NewCreateNotFound() *CreateNotFound {
	return &CreateNotFound{}
}

/*
CreateNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type CreateNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create not found response has a 2xx status code
func (o *CreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create not found response has a 3xx status code
func (o *CreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create not found response has a 4xx status code
func (o *CreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create not found response has a 5xx status code
func (o *CreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create not found response a status code equal to that given
func (o *CreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create not found response
func (o *CreateNotFound) Code() int {
	return 404
}

func (o *CreateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createNotFound %s", 404, payload)
}

func (o *CreateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createNotFound %s", 404, payload)
}

func (o *CreateNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInternalServerError creates a CreateInternalServerError with default headers values
func NewCreateInternalServerError() *CreateInternalServerError {
	return &CreateInternalServerError{}
}

/*
CreateInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type CreateInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create internal server error response has a 2xx status code
func (o *CreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create internal server error response has a 3xx status code
func (o *CreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create internal server error response has a 4xx status code
func (o *CreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create internal server error response has a 5xx status code
func (o *CreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create internal server error response a status code equal to that given
func (o *CreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create internal server error response
func (o *CreateInternalServerError) Code() int {
	return 500
}

func (o *CreateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createInternalServerError %s", 500, payload)
}

func (o *CreateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /n/nodes/create][%d] createInternalServerError %s", 500, payload)
}

func (o *CreateInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
