// Code generated by go-swagger; DO NOT EDIT.

package node_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	models2 "github.com/pydio/cells-sdk-go/v5/apiv2/models"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListNamespaceValuesReader is a Reader for the ListNamespaceValues structure.
type ListNamespaceValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNamespaceValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNamespaceValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListNamespaceValuesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListNamespaceValuesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListNamespaceValuesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListNamespaceValuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /n/meta/namespace/{Namespace}] ListNamespaceValues", response, response.Code())
	}
}

// NewListNamespaceValuesOK creates a ListNamespaceValuesOK with default headers values
func NewListNamespaceValuesOK() *ListNamespaceValuesOK {
	return &ListNamespaceValuesOK{}
}

/*
ListNamespaceValuesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListNamespaceValuesOK struct {
	Payload *models2.RestNamespaceValuesResponse
}

// IsSuccess returns true when this list namespace values o k response has a 2xx status code
func (o *ListNamespaceValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list namespace values o k response has a 3xx status code
func (o *ListNamespaceValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list namespace values o k response has a 4xx status code
func (o *ListNamespaceValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list namespace values o k response has a 5xx status code
func (o *ListNamespaceValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list namespace values o k response a status code equal to that given
func (o *ListNamespaceValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list namespace values o k response
func (o *ListNamespaceValuesOK) Code() int {
	return 200
}

func (o *ListNamespaceValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesOK %s", 200, payload)
}

func (o *ListNamespaceValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesOK %s", 200, payload)
}

func (o *ListNamespaceValuesOK) GetPayload() *models2.RestNamespaceValuesResponse {
	return o.Payload
}

func (o *ListNamespaceValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestNamespaceValuesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNamespaceValuesUnauthorized creates a ListNamespaceValuesUnauthorized with default headers values
func NewListNamespaceValuesUnauthorized() *ListNamespaceValuesUnauthorized {
	return &ListNamespaceValuesUnauthorized{}
}

/*
ListNamespaceValuesUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type ListNamespaceValuesUnauthorized struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this list namespace values unauthorized response has a 2xx status code
func (o *ListNamespaceValuesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list namespace values unauthorized response has a 3xx status code
func (o *ListNamespaceValuesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list namespace values unauthorized response has a 4xx status code
func (o *ListNamespaceValuesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list namespace values unauthorized response has a 5xx status code
func (o *ListNamespaceValuesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list namespace values unauthorized response a status code equal to that given
func (o *ListNamespaceValuesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list namespace values unauthorized response
func (o *ListNamespaceValuesUnauthorized) Code() int {
	return 401
}

func (o *ListNamespaceValuesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesUnauthorized %s", 401, payload)
}

func (o *ListNamespaceValuesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesUnauthorized %s", 401, payload)
}

func (o *ListNamespaceValuesUnauthorized) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *ListNamespaceValuesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNamespaceValuesForbidden creates a ListNamespaceValuesForbidden with default headers values
func NewListNamespaceValuesForbidden() *ListNamespaceValuesForbidden {
	return &ListNamespaceValuesForbidden{}
}

/*
ListNamespaceValuesForbidden describes a response with status code 403, with default header values.

User has no permission to access this particular resource
*/
type ListNamespaceValuesForbidden struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this list namespace values forbidden response has a 2xx status code
func (o *ListNamespaceValuesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list namespace values forbidden response has a 3xx status code
func (o *ListNamespaceValuesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list namespace values forbidden response has a 4xx status code
func (o *ListNamespaceValuesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list namespace values forbidden response has a 5xx status code
func (o *ListNamespaceValuesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list namespace values forbidden response a status code equal to that given
func (o *ListNamespaceValuesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the list namespace values forbidden response
func (o *ListNamespaceValuesForbidden) Code() int {
	return 403
}

func (o *ListNamespaceValuesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesForbidden %s", 403, payload)
}

func (o *ListNamespaceValuesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesForbidden %s", 403, payload)
}

func (o *ListNamespaceValuesForbidden) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *ListNamespaceValuesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNamespaceValuesNotFound creates a ListNamespaceValuesNotFound with default headers values
func NewListNamespaceValuesNotFound() *ListNamespaceValuesNotFound {
	return &ListNamespaceValuesNotFound{}
}

/*
ListNamespaceValuesNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type ListNamespaceValuesNotFound struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this list namespace values not found response has a 2xx status code
func (o *ListNamespaceValuesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list namespace values not found response has a 3xx status code
func (o *ListNamespaceValuesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list namespace values not found response has a 4xx status code
func (o *ListNamespaceValuesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list namespace values not found response has a 5xx status code
func (o *ListNamespaceValuesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list namespace values not found response a status code equal to that given
func (o *ListNamespaceValuesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list namespace values not found response
func (o *ListNamespaceValuesNotFound) Code() int {
	return 404
}

func (o *ListNamespaceValuesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesNotFound %s", 404, payload)
}

func (o *ListNamespaceValuesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesNotFound %s", 404, payload)
}

func (o *ListNamespaceValuesNotFound) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *ListNamespaceValuesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNamespaceValuesInternalServerError creates a ListNamespaceValuesInternalServerError with default headers values
func NewListNamespaceValuesInternalServerError() *ListNamespaceValuesInternalServerError {
	return &ListNamespaceValuesInternalServerError{}
}

/*
ListNamespaceValuesInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type ListNamespaceValuesInternalServerError struct {
	Payload *models2.RestError
}

// IsSuccess returns true when this list namespace values internal server error response has a 2xx status code
func (o *ListNamespaceValuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list namespace values internal server error response has a 3xx status code
func (o *ListNamespaceValuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list namespace values internal server error response has a 4xx status code
func (o *ListNamespaceValuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list namespace values internal server error response has a 5xx status code
func (o *ListNamespaceValuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list namespace values internal server error response a status code equal to that given
func (o *ListNamespaceValuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list namespace values internal server error response
func (o *ListNamespaceValuesInternalServerError) Code() int {
	return 500
}

func (o *ListNamespaceValuesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesInternalServerError %s", 500, payload)
}

func (o *ListNamespaceValuesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /n/meta/namespace/{Namespace}][%d] listNamespaceValuesInternalServerError %s", 500, payload)
}

func (o *ListNamespaceValuesInternalServerError) GetPayload() *models2.RestError {
	return o.Payload
}

func (o *ListNamespaceValuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models2.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
