/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CtlService struct {

	Name string `json:"Name,omitempty"`

	Version string `json:"Version,omitempty"`

	Description string `json:"Description,omitempty"`

	Tag string `json:"Tag,omitempty"`

	Controllable bool `json:"Controllable,omitempty"`

	Status *CtlServiceStatus `json:"Status,omitempty"`

	RunningPeers []CtlPeer `json:"RunningPeers,omitempty"`
}
