/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListSharedResourcesResponseSharedResource struct {

	Node *TreeNode `json:"Node,omitempty"`

	Link *RestShareLink `json:"Link,omitempty"`

	Cells []RestCell `json:"Cells,omitempty"`
}
