/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RestListSharedResourcesRequest struct {

	ShareType *ListSharedResourcesRequestListShareType `json:"ShareType,omitempty"`

	Subject string `json:"Subject,omitempty"`

	OwnedBySubject bool `json:"OwnedBySubject,omitempty"`

	Offset int32 `json:"Offset,omitempty"`

	Limit int32 `json:"Limit,omitempty"`
}
