/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TreeVersioningPolicy struct {

	Uuid string `json:"Uuid,omitempty"`

	Name string `json:"Name,omitempty"`

	Description string `json:"Description,omitempty"`

	VersionsDataSourceName string `json:"VersionsDataSourceName,omitempty"`

	VersionsDataSourceBucket string `json:"VersionsDataSourceBucket,omitempty"`

	MaxTotalSize string `json:"MaxTotalSize,omitempty"`

	MaxSizePerFile string `json:"MaxSizePerFile,omitempty"`

	IgnoreFilesGreaterThan string `json:"IgnoreFilesGreaterThan,omitempty"`

	KeepPeriods []TreeVersioningKeepPeriod `json:"KeepPeriods,omitempty"`
}
