// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/pydio/cells-sdk-go/models"
)

// ConfigFormsDiscoveryReader is a Reader for the ConfigFormsDiscovery structure.
type ConfigFormsDiscoveryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigFormsDiscoveryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewConfigFormsDiscoveryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConfigFormsDiscoveryOK creates a ConfigFormsDiscoveryOK with default headers values
func NewConfigFormsDiscoveryOK() *ConfigFormsDiscoveryOK {
	return &ConfigFormsDiscoveryOK{}
}

/*ConfigFormsDiscoveryOK handles this case with default header values.

ConfigFormsDiscoveryOK config forms discovery o k
*/
type ConfigFormsDiscoveryOK struct {
	Payload *models.RestDiscoveryResponse
}

func (o *ConfigFormsDiscoveryOK) Error() string {
	return fmt.Sprintf("[GET /config/discovery/forms/{ServiceName}][%d] configFormsDiscoveryOK  %+v", 200, o.Payload)
}

func (o *ConfigFormsDiscoveryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestDiscoveryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
