// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/pydio/cells-sdk-go/models"
)

// NewCreateEncryptionKeyParams creates a new CreateEncryptionKeyParams object
// with the default values initialized.
func NewCreateEncryptionKeyParams() *CreateEncryptionKeyParams {
	var ()
	return &CreateEncryptionKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEncryptionKeyParamsWithTimeout creates a new CreateEncryptionKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateEncryptionKeyParamsWithTimeout(timeout time.Duration) *CreateEncryptionKeyParams {
	var ()
	return &CreateEncryptionKeyParams{

		timeout: timeout,
	}
}

// NewCreateEncryptionKeyParamsWithContext creates a new CreateEncryptionKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateEncryptionKeyParamsWithContext(ctx context.Context) *CreateEncryptionKeyParams {
	var ()
	return &CreateEncryptionKeyParams{

		Context: ctx,
	}
}

// NewCreateEncryptionKeyParamsWithHTTPClient creates a new CreateEncryptionKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateEncryptionKeyParamsWithHTTPClient(client *http.Client) *CreateEncryptionKeyParams {
	var ()
	return &CreateEncryptionKeyParams{
		HTTPClient: client,
	}
}

/*CreateEncryptionKeyParams contains all the parameters to send to the API endpoint
for the create encryption key operation typically these are written to a http.Request
*/
type CreateEncryptionKeyParams struct {

	/*Body*/
	Body *models.EncryptionAdminCreateKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create encryption key params
func (o *CreateEncryptionKeyParams) WithTimeout(timeout time.Duration) *CreateEncryptionKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create encryption key params
func (o *CreateEncryptionKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create encryption key params
func (o *CreateEncryptionKeyParams) WithContext(ctx context.Context) *CreateEncryptionKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create encryption key params
func (o *CreateEncryptionKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create encryption key params
func (o *CreateEncryptionKeyParams) WithHTTPClient(client *http.Client) *CreateEncryptionKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create encryption key params
func (o *CreateEncryptionKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create encryption key params
func (o *CreateEncryptionKeyParams) WithBody(body *models.EncryptionAdminCreateKeyRequest) *CreateEncryptionKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create encryption key params
func (o *CreateEncryptionKeyParams) SetBody(body *models.EncryptionAdminCreateKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEncryptionKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
