// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/pydio/cells-sdk-go/models"
)

// OpenAPIDiscoveryReader is a Reader for the OpenAPIDiscovery structure.
type OpenAPIDiscoveryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OpenAPIDiscoveryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOpenAPIDiscoveryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOpenAPIDiscoveryOK creates a OpenAPIDiscoveryOK with default headers values
func NewOpenAPIDiscoveryOK() *OpenAPIDiscoveryOK {
	return &OpenAPIDiscoveryOK{}
}

/*OpenAPIDiscoveryOK handles this case with default header values.

OpenAPIDiscoveryOK open Api discovery o k
*/
type OpenAPIDiscoveryOK struct {
	Payload models.RestOpenAPIResponse
}

func (o *OpenAPIDiscoveryOK) Error() string {
	return fmt.Sprintf("[GET /config/discovery/openapi][%d] openApiDiscoveryOK  %+v", 200, o.Payload)
}

func (o *OpenAPIDiscoveryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
