// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSchedulerActionsDiscoveryParams creates a new SchedulerActionsDiscoveryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulerActionsDiscoveryParams() *SchedulerActionsDiscoveryParams {
	return &SchedulerActionsDiscoveryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerActionsDiscoveryParamsWithTimeout creates a new SchedulerActionsDiscoveryParams object
// with the ability to set a timeout on a request.
func NewSchedulerActionsDiscoveryParamsWithTimeout(timeout time.Duration) *SchedulerActionsDiscoveryParams {
	return &SchedulerActionsDiscoveryParams{
		timeout: timeout,
	}
}

// NewSchedulerActionsDiscoveryParamsWithContext creates a new SchedulerActionsDiscoveryParams object
// with the ability to set a context for a request.
func NewSchedulerActionsDiscoveryParamsWithContext(ctx context.Context) *SchedulerActionsDiscoveryParams {
	return &SchedulerActionsDiscoveryParams{
		Context: ctx,
	}
}

// NewSchedulerActionsDiscoveryParamsWithHTTPClient creates a new SchedulerActionsDiscoveryParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulerActionsDiscoveryParamsWithHTTPClient(client *http.Client) *SchedulerActionsDiscoveryParams {
	return &SchedulerActionsDiscoveryParams{
		HTTPClient: client,
	}
}

/*
SchedulerActionsDiscoveryParams contains all the parameters to send to the API endpoint

	for the scheduler actions discovery operation.

	Typically these are written to a http.Request.
*/
type SchedulerActionsDiscoveryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scheduler actions discovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerActionsDiscoveryParams) WithDefaults() *SchedulerActionsDiscoveryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scheduler actions discovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerActionsDiscoveryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) WithTimeout(timeout time.Duration) *SchedulerActionsDiscoveryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) WithContext(ctx context.Context) *SchedulerActionsDiscoveryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) WithHTTPClient(client *http.Client) *SchedulerActionsDiscoveryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler actions discovery params
func (o *SchedulerActionsDiscoveryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerActionsDiscoveryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
