// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// LookupFilterMetaFilterOp lookup filter meta filter op
//
// swagger:model LookupFilterMetaFilterOp
type LookupFilterMetaFilterOp string

func NewLookupFilterMetaFilterOp(value LookupFilterMetaFilterOp) *LookupFilterMetaFilterOp {
	return &value
}

// Pointer returns a pointer to a freshly-allocated LookupFilterMetaFilterOp.
func (m LookupFilterMetaFilterOp) Pointer() *LookupFilterMetaFilterOp {
	return &m
}

const (

	// LookupFilterMetaFilterOpMust captures enum value "Must"
	LookupFilterMetaFilterOpMust LookupFilterMetaFilterOp = "Must"

	// LookupFilterMetaFilterOpShould captures enum value "Should"
	LookupFilterMetaFilterOpShould LookupFilterMetaFilterOp = "Should"

	// LookupFilterMetaFilterOpNot captures enum value "Not"
	LookupFilterMetaFilterOpNot LookupFilterMetaFilterOp = "Not"
)

// for schema
var lookupFilterMetaFilterOpEnum []interface{}

func init() {
	var res []LookupFilterMetaFilterOp
	if err := json.Unmarshal([]byte(`["Must","Should","Not"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lookupFilterMetaFilterOpEnum = append(lookupFilterMetaFilterOpEnum, v)
	}
}

func (m LookupFilterMetaFilterOp) validateLookupFilterMetaFilterOpEnum(path, location string, value LookupFilterMetaFilterOp) error {
	if err := validate.EnumCase(path, location, value, lookupFilterMetaFilterOpEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this lookup filter meta filter op
func (m LookupFilterMetaFilterOp) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLookupFilterMetaFilterOpEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this lookup filter meta filter op based on context it is used
func (m LookupFilterMetaFilterOp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
