// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestNamespaceValuesResponse Response for Namespaces values
//
// swagger:model restNamespaceValuesResponse
type RestNamespaceValuesResponse struct {

	// List of existing values
	Values []string `json:"Values"`
}

// Validate validates this rest namespace values response
func (m *RestNamespaceValuesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest namespace values response based on context it is used
func (m *RestNamespaceValuesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestNamespaceValuesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestNamespaceValuesResponse) UnmarshalBinary(b []byte) error {
	var res RestNamespaceValuesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
