// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RestVersion rest version
//
// swagger:model restVersion
type RestVersion struct {

	// ContentHash
	ContentHash string `json:"ContentHash,omitempty"`

	// Human-readable description of what happened
	Description string `json:"Description,omitempty"`

	// This revision is not published
	Draft bool `json:"Draft,omitempty"`

	// Storage ETag
	ETag string `json:"ETag,omitempty"`

	// This revision is actually the current HEAD
	IsHead bool `json:"IsHead,omitempty"`

	// Unix Timestamp
	MTime string `json:"MTime,omitempty"`

	// Who performed this action - name
	OwnerName string `json:"OwnerName,omitempty"`

	// Who performed this action - uuid
	OwnerUUID string `json:"OwnerUuid,omitempty"`

	// Content Size at that moment
	Size string `json:"Size,omitempty"`

	// Unique commit ID
	// Required: true
	VersionID *string `json:"VersionId"`
}

// Validate validates this rest version
func (m *RestVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RestVersion) validateVersionID(formats strfmt.Registry) error {

	if err := validate.Required("VersionId", "body", m.VersionID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this rest version based on context it is used
func (m *RestVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestVersion) UnmarshalBinary(b []byte) error {
	var res RestVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
