// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RestPutUserMetaTagRequest rest put user meta tag request
// swagger:model restPutUserMetaTagRequest
type RestPutUserMetaTagRequest struct {

	// Add a tag value for this namespace
	Namespace string `json:"Namespace,omitempty"`

	// New tag value
	Tag string `json:"Tag,omitempty"`
}

// Validate validates this rest put user meta tag request
func (m *RestPutUserMetaTagRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestPutUserMetaTagRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestPutUserMetaTagRequest) UnmarshalBinary(b []byte) error {
	var res RestPutUserMetaTagRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
