// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSchedulerActionFormDiscoveryParams creates a new SchedulerActionFormDiscoveryParams object
// with the default values initialized.
func NewSchedulerActionFormDiscoveryParams() *SchedulerActionFormDiscoveryParams {
	var ()
	return &SchedulerActionFormDiscoveryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerActionFormDiscoveryParamsWithTimeout creates a new SchedulerActionFormDiscoveryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSchedulerActionFormDiscoveryParamsWithTimeout(timeout time.Duration) *SchedulerActionFormDiscoveryParams {
	var ()
	return &SchedulerActionFormDiscoveryParams{

		timeout: timeout,
	}
}

// NewSchedulerActionFormDiscoveryParamsWithContext creates a new SchedulerActionFormDiscoveryParams object
// with the default values initialized, and the ability to set a context for a request
func NewSchedulerActionFormDiscoveryParamsWithContext(ctx context.Context) *SchedulerActionFormDiscoveryParams {
	var ()
	return &SchedulerActionFormDiscoveryParams{

		Context: ctx,
	}
}

// NewSchedulerActionFormDiscoveryParamsWithHTTPClient creates a new SchedulerActionFormDiscoveryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSchedulerActionFormDiscoveryParamsWithHTTPClient(client *http.Client) *SchedulerActionFormDiscoveryParams {
	var ()
	return &SchedulerActionFormDiscoveryParams{
		HTTPClient: client,
	}
}

/*SchedulerActionFormDiscoveryParams contains all the parameters to send to the API endpoint
for the scheduler action form discovery operation typically these are written to a http.Request
*/
type SchedulerActionFormDiscoveryParams struct {

	/*ActionName*/
	ActionName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) WithTimeout(timeout time.Duration) *SchedulerActionFormDiscoveryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) WithContext(ctx context.Context) *SchedulerActionFormDiscoveryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) WithHTTPClient(client *http.Client) *SchedulerActionFormDiscoveryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActionName adds the actionName to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) WithActionName(actionName string) *SchedulerActionFormDiscoveryParams {
	o.SetActionName(actionName)
	return o
}

// SetActionName adds the actionName to the scheduler action form discovery params
func (o *SchedulerActionFormDiscoveryParams) SetActionName(actionName string) {
	o.ActionName = actionName
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerActionFormDiscoveryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ActionName
	if err := r.SetPathParam("ActionName", o.ActionName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
