// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v3/models"
)

// ListSitesReader is a Reader for the ListSites structure.
type ListSitesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSitesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSitesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListSitesOK creates a ListSitesOK with default headers values
func NewListSitesOK() *ListSitesOK {
	return &ListSitesOK{}
}

/* ListSitesOK describes a response with status code 200, with default header values.

ListSitesOK list sites o k
*/
type ListSitesOK struct {
	Payload *models.RestListSitesResponse
}

func (o *ListSitesOK) Error() string {
	return fmt.Sprintf("[GET /config/sites/{Filter}][%d] listSitesOK  %+v", 200, o.Payload)
}
func (o *ListSitesOK) GetPayload() *models.RestListSitesResponse {
	return o.Payload
}

func (o *ListSitesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestListSitesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
