// Code generated by go-swagger; DO NOT EDIT.

package config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v3/models"
)

// NewListStorageBucketsParams creates a new ListStorageBucketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListStorageBucketsParams() *ListStorageBucketsParams {
	return &ListStorageBucketsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListStorageBucketsParamsWithTimeout creates a new ListStorageBucketsParams object
// with the ability to set a timeout on a request.
func NewListStorageBucketsParamsWithTimeout(timeout time.Duration) *ListStorageBucketsParams {
	return &ListStorageBucketsParams{
		timeout: timeout,
	}
}

// NewListStorageBucketsParamsWithContext creates a new ListStorageBucketsParams object
// with the ability to set a context for a request.
func NewListStorageBucketsParamsWithContext(ctx context.Context) *ListStorageBucketsParams {
	return &ListStorageBucketsParams{
		Context: ctx,
	}
}

// NewListStorageBucketsParamsWithHTTPClient creates a new ListStorageBucketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListStorageBucketsParamsWithHTTPClient(client *http.Client) *ListStorageBucketsParams {
	return &ListStorageBucketsParams{
		HTTPClient: client,
	}
}

/* ListStorageBucketsParams contains all the parameters to send to the API endpoint
   for the list storage buckets operation.

   Typically these are written to a http.Request.
*/
type ListStorageBucketsParams struct {

	// Body.
	Body *models.RestListStorageBucketsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list storage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListStorageBucketsParams) WithDefaults() *ListStorageBucketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list storage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListStorageBucketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list storage buckets params
func (o *ListStorageBucketsParams) WithTimeout(timeout time.Duration) *ListStorageBucketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list storage buckets params
func (o *ListStorageBucketsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list storage buckets params
func (o *ListStorageBucketsParams) WithContext(ctx context.Context) *ListStorageBucketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list storage buckets params
func (o *ListStorageBucketsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list storage buckets params
func (o *ListStorageBucketsParams) WithHTTPClient(client *http.Client) *ListStorageBucketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list storage buckets params
func (o *ListStorageBucketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list storage buckets params
func (o *ListStorageBucketsParams) WithBody(body *models.RestListStorageBucketsRequest) *ListStorageBucketsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list storage buckets params
func (o *ListStorageBucketsParams) SetBody(body *models.RestListStorageBucketsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListStorageBucketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
