// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActivitySearchSubscriptionsRequest activity search subscriptions request
//
// swagger:model activitySearchSubscriptionsRequest
type ActivitySearchSubscriptionsRequest struct {

	// Filter by object Ids
	ObjectIds []string `json:"ObjectIds"`

	// Filter by type of objects
	ObjectTypes []*ActivityOwnerType `json:"ObjectTypes"`

	// List of UserIds for which we want to list
	UserIds []string `json:"UserIds"`
}

// Validate validates this activity search subscriptions request
func (m *ActivitySearchSubscriptionsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObjectTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivitySearchSubscriptionsRequest) validateObjectTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.ObjectTypes) { // not required
		return nil
	}

	for i := 0; i < len(m.ObjectTypes); i++ {
		if swag.IsZero(m.ObjectTypes[i]) { // not required
			continue
		}

		if m.ObjectTypes[i] != nil {
			if err := m.ObjectTypes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ObjectTypes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ObjectTypes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this activity search subscriptions request based on the context it is used
func (m *ActivitySearchSubscriptionsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateObjectTypes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivitySearchSubscriptionsRequest) contextValidateObjectTypes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ObjectTypes); i++ {

		if m.ObjectTypes[i] != nil {

			if swag.IsZero(m.ObjectTypes[i]) { // not required
				return nil
			}

			if err := m.ObjectTypes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ObjectTypes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ObjectTypes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActivitySearchSubscriptionsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivitySearchSubscriptionsRequest) UnmarshalBinary(b []byte) error {
	var res ActivitySearchSubscriptionsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
