// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdmListPolicyGroupsRequest idm list policy groups request
//
// swagger:model idmListPolicyGroupsRequest
type IdmListPolicyGroupsRequest struct {

	// filter
	Filter string `json:"Filter,omitempty"`
}

// Validate validates this idm list policy groups request
func (m *IdmListPolicyGroupsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this idm list policy groups request based on context it is used
func (m *IdmListPolicyGroupsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdmListPolicyGroupsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdmListPolicyGroupsRequest) UnmarshalBinary(b []byte) error {
	var res IdmListPolicyGroupsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
