// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdmDeleteEntityResponse idm delete entity response
//
// swagger:model idmDeleteEntityResponse
type IdmDeleteEntityResponse struct {

	// rows deleted
	RowsDeleted string `json:"RowsDeleted,omitempty"`
}

// Validate validates this idm delete entity response
func (m *IdmDeleteEntityResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this idm delete entity response based on context it is used
func (m *IdmDeleteEntityResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdmDeleteEntityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdmDeleteEntityResponse) UnmarshalBinary(b []byte) error {
	var res IdmDeleteEntityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
