// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdmCreateEntityRequest Creates a new Entity request
//
// swagger:model idmCreateEntityRequest
type IdmCreateEntityRequest struct {

	// entity
	Entity *IdmMetaEntity `json:"Entity,omitempty"`
}

// Validate validates this idm create entity request
func (m *IdmCreateEntityRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdmCreateEntityRequest) validateEntity(formats strfmt.Registry) error {
	if swag.IsZero(m.Entity) { // not required
		return nil
	}

	if m.Entity != nil {
		if err := m.Entity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Entity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Entity")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this idm create entity request based on the context it is used
func (m *IdmCreateEntityRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEntity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdmCreateEntityRequest) contextValidateEntity(ctx context.Context, formats strfmt.Registry) error {

	if m.Entity != nil {

		if swag.IsZero(m.Entity) { // not required
			return nil
		}

		if err := m.Entity.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Entity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Entity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IdmCreateEntityRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdmCreateEntityRequest) UnmarshalBinary(b []byte) error {
	var res IdmCreateEntityRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
