// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstallTLSLetsEncrypt TLSLetsEncrypt set up proxy to automatically get a valid certificate from let's encrypt servers
//
// swagger:model installTLSLetsEncrypt
type InstallTLSLetsEncrypt struct {

	// accept e u l a
	AcceptEULA bool `json:"AcceptEULA,omitempty"`

	// email
	Email string `json:"Email,omitempty"`

	// staging c a
	StagingCA bool `json:"StagingCA,omitempty"`
}

// Validate validates this install TLS lets encrypt
func (m *InstallTLSLetsEncrypt) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this install TLS lets encrypt based on context it is used
func (m *InstallTLSLetsEncrypt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstallTLSLetsEncrypt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstallTLSLetsEncrypt) UnmarshalBinary(b []byte) error {
	var res InstallTLSLetsEncrypt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
