// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// InstallRuleEffect install rule effect
//
// swagger:model installRuleEffect
type InstallRuleEffect string

func NewInstallRuleEffect(value InstallRuleEffect) *InstallRuleEffect {
	return &value
}

// Pointer returns a pointer to a freshly-allocated InstallRuleEffect.
func (m InstallRuleEffect) Pointer() *InstallRuleEffect {
	return &m
}

const (

	// InstallRuleEffectDENY captures enum value "DENY"
	InstallRuleEffectDENY InstallRuleEffect = "DENY"

	// InstallRuleEffectACCEPT captures enum value "ACCEPT"
	InstallRuleEffectACCEPT InstallRuleEffect = "ACCEPT"
)

// for schema
var installRuleEffectEnum []interface{}

func init() {
	var res []InstallRuleEffect
	if err := json.Unmarshal([]byte(`["DENY","ACCEPT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		installRuleEffectEnum = append(installRuleEffectEnum, v)
	}
}

func (m InstallRuleEffect) validateInstallRuleEffectEnum(path, location string, value InstallRuleEffect) error {
	if err := validate.EnumCase(path, location, value, installRuleEffectEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this install rule effect
func (m InstallRuleEffect) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateInstallRuleEffectEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this install rule effect based on context it is used
func (m InstallRuleEffect) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
