// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstallInstallEventsResponse install install events response
//
// swagger:model installInstallEventsResponse
type InstallInstallEventsResponse struct {

	// success
	Success bool `json:"Success,omitempty"`
}

// Validate validates this install install events response
func (m *InstallInstallEventsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this install install events response based on context it is used
func (m *InstallInstallEventsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstallInstallEventsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstallInstallEventsResponse) UnmarshalBinary(b []byte) error {
	var res InstallInstallEventsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
