// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegistryNode registry node
//
// swagger:model registryNode
type RegistryNode struct {

	// advertise Ip
	AdvertiseIP string `json:"advertiseIp,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// ips
	Ips []string `json:"ips"`

	// machine
	Machine string `json:"machine,omitempty"`
}

// Validate validates this registry node
func (m *RegistryNode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this registry node based on context it is used
func (m *RegistryNode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistryNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistryNode) UnmarshalBinary(b []byte) error {
	var res RegistryNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
