// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestUserBookmarksRequest rest user bookmarks request
//
// swagger:model restUserBookmarksRequest
type RestUserBookmarksRequest struct {

	// all
	All bool `json:"All,omitempty"`
}

// Validate validates this rest user bookmarks request
func (m *RestUserBookmarksRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest user bookmarks request based on context it is used
func (m *RestUserBookmarksRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestUserBookmarksRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestUserBookmarksRequest) UnmarshalBinary(b []byte) error {
	var res RestUserBookmarksRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
