// Code generated by go-swagger; DO NOT EDIT.

package meta_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v3/models"
)

// NewGetBulkMetaParams creates a new GetBulkMetaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBulkMetaParams() *GetBulkMetaParams {
	return &GetBulkMetaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBulkMetaParamsWithTimeout creates a new GetBulkMetaParams object
// with the ability to set a timeout on a request.
func NewGetBulkMetaParamsWithTimeout(timeout time.Duration) *GetBulkMetaParams {
	return &GetBulkMetaParams{
		timeout: timeout,
	}
}

// NewGetBulkMetaParamsWithContext creates a new GetBulkMetaParams object
// with the ability to set a context for a request.
func NewGetBulkMetaParamsWithContext(ctx context.Context) *GetBulkMetaParams {
	return &GetBulkMetaParams{
		Context: ctx,
	}
}

// NewGetBulkMetaParamsWithHTTPClient creates a new GetBulkMetaParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBulkMetaParamsWithHTTPClient(client *http.Client) *GetBulkMetaParams {
	return &GetBulkMetaParams{
		HTTPClient: client,
	}
}

/* GetBulkMetaParams contains all the parameters to send to the API endpoint
   for the get bulk meta operation.

   Typically these are written to a http.Request.
*/
type GetBulkMetaParams struct {

	// Body.
	Body *models.RestGetBulkMetaRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bulk meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBulkMetaParams) WithDefaults() *GetBulkMetaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bulk meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBulkMetaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bulk meta params
func (o *GetBulkMetaParams) WithTimeout(timeout time.Duration) *GetBulkMetaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bulk meta params
func (o *GetBulkMetaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bulk meta params
func (o *GetBulkMetaParams) WithContext(ctx context.Context) *GetBulkMetaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bulk meta params
func (o *GetBulkMetaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bulk meta params
func (o *GetBulkMetaParams) WithHTTPClient(client *http.Client) *GetBulkMetaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bulk meta params
func (o *GetBulkMetaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get bulk meta params
func (o *GetBulkMetaParams) WithBody(body *models.RestGetBulkMetaRequest) *GetBulkMetaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get bulk meta params
func (o *GetBulkMetaParams) SetBody(body *models.RestGetBulkMetaRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetBulkMetaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
