// Code generated by go-swagger; DO NOT EDIT.

package enterprise_log_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/pydio/cells-sdk-go/models"
)

// AuditChartDataReader is a Reader for the AuditChartData structure.
type AuditChartDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuditChartDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAuditChartDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAuditChartDataOK creates a AuditChartDataOK with default headers values
func NewAuditChartDataOK() *AuditChartDataOK {
	return &AuditChartDataOK{}
}

/*AuditChartDataOK handles this case with default header values.

AuditChartDataOK audit chart data o k
*/
type AuditChartDataOK struct {
	Payload *models.RestTimeRangeResultCollection
}

func (o *AuditChartDataOK) Error() string {
	return fmt.Sprintf("[POST /log/audit/chartdata][%d] auditChartDataOK  %+v", 200, o.Payload)
}

func (o *AuditChartDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestTimeRangeResultCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
