/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type DocstoreDeleteDocumentsResponse struct {

	Success bool `json:"Success,omitempty"`

	DeletionCount int32 `json:"DeletionCount,omitempty"`
}
