/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type IdmUser struct {

	Uuid string `json:"Uuid,omitempty"`

	GroupPath string `json:"GroupPath,omitempty"`

	Attributes map[string]string `json:"Attributes,omitempty"`

	Roles []IdmRole `json:"Roles,omitempty"`

	Login string `json:"Login,omitempty"`

	Password string `json:"Password,omitempty"`

	IsGroup bool `json:"IsGroup,omitempty"`

	GroupLabel string `json:"GroupLabel,omitempty"`

	Policies []ServiceResourcePolicy `json:"Policies,omitempty"`

	PoliciesContextEditable bool `json:"PoliciesContextEditable,omitempty"`
}
