/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type IdmRoleSingleQuery struct {

	Uuid []string `json:"Uuid,omitempty"`

	Label string `json:"Label,omitempty"`

	IsTeam bool `json:"IsTeam,omitempty"`

	IsGroupRole bool `json:"IsGroupRole,omitempty"`

	IsUserRole bool `json:"IsUserRole,omitempty"`

	HasAutoApply bool `json:"HasAutoApply,omitempty"`

	Not bool `json:"not,omitempty"`
}
