/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type IdmAclSingleQuery struct {

	Actions []IdmAclAction `json:"Actions,omitempty"`

	RoleIDs []string `json:"RoleIDs,omitempty"`

	WorkspaceIDs []string `json:"WorkspaceIDs,omitempty"`

	NodeIDs []string `json:"NodeIDs,omitempty"`

	Not bool `json:"not,omitempty"`
}
