/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type RestSearchRoleRequest struct {

	Queries []IdmRoleSingleQuery `json:"Queries,omitempty"`

	ResourcePolicyQuery *RestResourcePolicyQuery `json:"ResourcePolicyQuery,omitempty"`

	Offset string `json:"Offset,omitempty"`

	Limit string `json:"Limit,omitempty"`

	GroupBy int32 `json:"GroupBy,omitempty"`

	CountOnly bool `json:"CountOnly,omitempty"`

	Operation *ServiceOperationType `json:"Operation,omitempty"`
}
