/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type TreeNodeType string

// List of treeNodeType
const (
	TNT_UNKNOWN    TreeNodeType = "UNKNOWN"
	TNT_LEAF       TreeNodeType = "LEAF"
	TNT_COLLECTION TreeNodeType = "COLLECTION"
)
