/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type TreeSyncChangeType string

// List of treeSyncChangeType
const (
	TSCT_UNKNOWN TreeSyncChangeType = "unknown"
	TSCT_CREATE  TreeSyncChangeType = "create"
	TSCT_DELETE  TreeSyncChangeType = "delete"
	TSCT_PATH    TreeSyncChangeType = "path"
	TSCT_CONTENT TreeSyncChangeType = "content"
)
