/*
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type TreeReadNodeRequest struct {

	Node *TreeNode `json:"Node,omitempty"`

	WithCommits bool `json:"WithCommits,omitempty"`
}
