// Code generated by go-swagger; DO NOT EDIT.

package tree_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v4/models"
)

// BulkStatNodesReader is a Reader for the BulkStatNodes structure.
type BulkStatNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkStatNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBulkStatNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewBulkStatNodesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBulkStatNodesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBulkStatNodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkStatNodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /tree/stats] BulkStatNodes", response, response.Code())
	}
}

// NewBulkStatNodesOK creates a BulkStatNodesOK with default headers values
func NewBulkStatNodesOK() *BulkStatNodesOK {
	return &BulkStatNodesOK{}
}

/*
BulkStatNodesOK describes a response with status code 200, with default header values.

A successful response.
*/
type BulkStatNodesOK struct {
	Payload *models.RestBulkMetaResponse
}

// IsSuccess returns true when this bulk stat nodes o k response has a 2xx status code
func (o *BulkStatNodesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this bulk stat nodes o k response has a 3xx status code
func (o *BulkStatNodesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk stat nodes o k response has a 4xx status code
func (o *BulkStatNodesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk stat nodes o k response has a 5xx status code
func (o *BulkStatNodesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk stat nodes o k response a status code equal to that given
func (o *BulkStatNodesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the bulk stat nodes o k response
func (o *BulkStatNodesOK) Code() int {
	return 200
}

func (o *BulkStatNodesOK) Error() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesOK  %+v", 200, o.Payload)
}

func (o *BulkStatNodesOK) String() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesOK  %+v", 200, o.Payload)
}

func (o *BulkStatNodesOK) GetPayload() *models.RestBulkMetaResponse {
	return o.Payload
}

func (o *BulkStatNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestBulkMetaResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkStatNodesUnauthorized creates a BulkStatNodesUnauthorized with default headers values
func NewBulkStatNodesUnauthorized() *BulkStatNodesUnauthorized {
	return &BulkStatNodesUnauthorized{}
}

/*
BulkStatNodesUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type BulkStatNodesUnauthorized struct {
}

// IsSuccess returns true when this bulk stat nodes unauthorized response has a 2xx status code
func (o *BulkStatNodesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk stat nodes unauthorized response has a 3xx status code
func (o *BulkStatNodesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk stat nodes unauthorized response has a 4xx status code
func (o *BulkStatNodesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk stat nodes unauthorized response has a 5xx status code
func (o *BulkStatNodesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk stat nodes unauthorized response a status code equal to that given
func (o *BulkStatNodesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the bulk stat nodes unauthorized response
func (o *BulkStatNodesUnauthorized) Code() int {
	return 401
}

func (o *BulkStatNodesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesUnauthorized ", 401)
}

func (o *BulkStatNodesUnauthorized) String() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesUnauthorized ", 401)
}

func (o *BulkStatNodesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBulkStatNodesForbidden creates a BulkStatNodesForbidden with default headers values
func NewBulkStatNodesForbidden() *BulkStatNodesForbidden {
	return &BulkStatNodesForbidden{}
}

/*
BulkStatNodesForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type BulkStatNodesForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this bulk stat nodes forbidden response has a 2xx status code
func (o *BulkStatNodesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk stat nodes forbidden response has a 3xx status code
func (o *BulkStatNodesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk stat nodes forbidden response has a 4xx status code
func (o *BulkStatNodesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk stat nodes forbidden response has a 5xx status code
func (o *BulkStatNodesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk stat nodes forbidden response a status code equal to that given
func (o *BulkStatNodesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the bulk stat nodes forbidden response
func (o *BulkStatNodesForbidden) Code() int {
	return 403
}

func (o *BulkStatNodesForbidden) Error() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesForbidden  %+v", 403, o.Payload)
}

func (o *BulkStatNodesForbidden) String() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesForbidden  %+v", 403, o.Payload)
}

func (o *BulkStatNodesForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *BulkStatNodesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkStatNodesNotFound creates a BulkStatNodesNotFound with default headers values
func NewBulkStatNodesNotFound() *BulkStatNodesNotFound {
	return &BulkStatNodesNotFound{}
}

/*
BulkStatNodesNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type BulkStatNodesNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this bulk stat nodes not found response has a 2xx status code
func (o *BulkStatNodesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk stat nodes not found response has a 3xx status code
func (o *BulkStatNodesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk stat nodes not found response has a 4xx status code
func (o *BulkStatNodesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk stat nodes not found response has a 5xx status code
func (o *BulkStatNodesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk stat nodes not found response a status code equal to that given
func (o *BulkStatNodesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the bulk stat nodes not found response
func (o *BulkStatNodesNotFound) Code() int {
	return 404
}

func (o *BulkStatNodesNotFound) Error() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesNotFound  %+v", 404, o.Payload)
}

func (o *BulkStatNodesNotFound) String() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesNotFound  %+v", 404, o.Payload)
}

func (o *BulkStatNodesNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *BulkStatNodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkStatNodesInternalServerError creates a BulkStatNodesInternalServerError with default headers values
func NewBulkStatNodesInternalServerError() *BulkStatNodesInternalServerError {
	return &BulkStatNodesInternalServerError{}
}

/*
BulkStatNodesInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type BulkStatNodesInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this bulk stat nodes internal server error response has a 2xx status code
func (o *BulkStatNodesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk stat nodes internal server error response has a 3xx status code
func (o *BulkStatNodesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk stat nodes internal server error response has a 4xx status code
func (o *BulkStatNodesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk stat nodes internal server error response has a 5xx status code
func (o *BulkStatNodesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this bulk stat nodes internal server error response a status code equal to that given
func (o *BulkStatNodesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the bulk stat nodes internal server error response
func (o *BulkStatNodesInternalServerError) Code() int {
	return 500
}

func (o *BulkStatNodesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesInternalServerError  %+v", 500, o.Payload)
}

func (o *BulkStatNodesInternalServerError) String() string {
	return fmt.Sprintf("[POST /tree/stats][%d] bulkStatNodesInternalServerError  %+v", 500, o.Payload)
}

func (o *BulkStatNodesInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *BulkStatNodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
