// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CtlPeer ctl peer
// swagger:model ctlPeer
type CtlPeer struct {

	// address
	Address string `json:"Address,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`

	// metadata
	Metadata map[string]string `json:"Metadata,omitempty"`

	// port
	Port int32 `json:"Port,omitempty"`
}

// Validate validates this ctl peer
func (m *CtlPeer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CtlPeer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CtlPeer) UnmarshalBinary(b []byte) error {
	var res CtlPeer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
