// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RestExternalDirectoryResponse rest external directory response
// swagger:model restExternalDirectoryResponse
type RestExternalDirectoryResponse struct {

	// success
	Success bool `json:"Success,omitempty"`
}

// Validate validates this rest external directory response
func (m *RestExternalDirectoryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestExternalDirectoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestExternalDirectoryResponse) UnmarshalBinary(b []byte) error {
	var res RestExternalDirectoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
