// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestLockInfo rest lock info
//
// swagger:model restLockInfo
type RestLockInfo struct {

	// is locked
	IsLocked bool `json:"IsLocked,omitempty"`

	// owner
	Owner string `json:"Owner,omitempty"`
}

// Validate validates this rest lock info
func (m *RestLockInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest lock info based on context it is used
func (m *RestLockInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestLockInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestLockInfo) UnmarshalBinary(b []byte) error {
	var res RestLockInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
