// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RestSettingsEntry rest settings entry
// swagger:model restSettingsEntry
type RestSettingsEntry struct {

	// alias
	Alias string `json:"Alias,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// key
	Key string `json:"Key,omitempty"`

	// label
	Label string `json:"Label,omitempty"`

	// manager
	Manager string `json:"Manager,omitempty"`

	// metadata
	Metadata *RestSettingsEntryMeta `json:"Metadata,omitempty"`
}

// Validate validates this rest settings entry
func (m *RestSettingsEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RestSettingsEntry) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RestSettingsEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestSettingsEntry) UnmarshalBinary(b []byte) error {
	var res RestSettingsEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
