// Code generated by go-swagger; DO NOT EDIT.

package token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-sdk-go/v4/models"
)

// RevokeReader is a Reader for the Revoke structure.
type RevokeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRevokeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRevokeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/token/revoke] Revoke", response, response.Code())
	}
}

// NewRevokeOK creates a RevokeOK with default headers values
func NewRevokeOK() *RevokeOK {
	return &RevokeOK{}
}

/*
RevokeOK describes a response with status code 200, with default header values.

A successful response.
*/
type RevokeOK struct {
	Payload *models.RestRevokeResponse
}

// IsSuccess returns true when this revoke o k response has a 2xx status code
func (o *RevokeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revoke o k response has a 3xx status code
func (o *RevokeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke o k response has a 4xx status code
func (o *RevokeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke o k response has a 5xx status code
func (o *RevokeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke o k response a status code equal to that given
func (o *RevokeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revoke o k response
func (o *RevokeOK) Code() int {
	return 200
}

func (o *RevokeOK) Error() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeOK  %+v", 200, o.Payload)
}

func (o *RevokeOK) String() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeOK  %+v", 200, o.Payload)
}

func (o *RevokeOK) GetPayload() *models.RestRevokeResponse {
	return o.Payload
}

func (o *RevokeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestRevokeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeUnauthorized creates a RevokeUnauthorized with default headers values
func NewRevokeUnauthorized() *RevokeUnauthorized {
	return &RevokeUnauthorized{}
}

/*
RevokeUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type RevokeUnauthorized struct {
}

// IsSuccess returns true when this revoke unauthorized response has a 2xx status code
func (o *RevokeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke unauthorized response has a 3xx status code
func (o *RevokeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke unauthorized response has a 4xx status code
func (o *RevokeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke unauthorized response has a 5xx status code
func (o *RevokeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke unauthorized response a status code equal to that given
func (o *RevokeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the revoke unauthorized response
func (o *RevokeUnauthorized) Code() int {
	return 401
}

func (o *RevokeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeUnauthorized ", 401)
}

func (o *RevokeUnauthorized) String() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeUnauthorized ", 401)
}

func (o *RevokeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeForbidden creates a RevokeForbidden with default headers values
func NewRevokeForbidden() *RevokeForbidden {
	return &RevokeForbidden{}
}

/*
RevokeForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type RevokeForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this revoke forbidden response has a 2xx status code
func (o *RevokeForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke forbidden response has a 3xx status code
func (o *RevokeForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke forbidden response has a 4xx status code
func (o *RevokeForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke forbidden response has a 5xx status code
func (o *RevokeForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke forbidden response a status code equal to that given
func (o *RevokeForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the revoke forbidden response
func (o *RevokeForbidden) Code() int {
	return 403
}

func (o *RevokeForbidden) Error() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeForbidden  %+v", 403, o.Payload)
}

func (o *RevokeForbidden) String() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeForbidden  %+v", 403, o.Payload)
}

func (o *RevokeForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeNotFound creates a RevokeNotFound with default headers values
func NewRevokeNotFound() *RevokeNotFound {
	return &RevokeNotFound{}
}

/*
RevokeNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type RevokeNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this revoke not found response has a 2xx status code
func (o *RevokeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke not found response has a 3xx status code
func (o *RevokeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke not found response has a 4xx status code
func (o *RevokeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke not found response has a 5xx status code
func (o *RevokeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke not found response a status code equal to that given
func (o *RevokeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the revoke not found response
func (o *RevokeNotFound) Code() int {
	return 404
}

func (o *RevokeNotFound) Error() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeNotFound  %+v", 404, o.Payload)
}

func (o *RevokeNotFound) String() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeNotFound  %+v", 404, o.Payload)
}

func (o *RevokeNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeInternalServerError creates a RevokeInternalServerError with default headers values
func NewRevokeInternalServerError() *RevokeInternalServerError {
	return &RevokeInternalServerError{}
}

/*
RevokeInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type RevokeInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this revoke internal server error response has a 2xx status code
func (o *RevokeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke internal server error response has a 3xx status code
func (o *RevokeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke internal server error response has a 4xx status code
func (o *RevokeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke internal server error response has a 5xx status code
func (o *RevokeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this revoke internal server error response a status code equal to that given
func (o *RevokeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the revoke internal server error response
func (o *RevokeInternalServerError) Code() int {
	return 500
}

func (o *RevokeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeInternalServerError  %+v", 500, o.Payload)
}

func (o *RevokeInternalServerError) String() string {
	return fmt.Sprintf("[POST /auth/token/revoke][%d] revokeInternalServerError  %+v", 500, o.Payload)
}

func (o *RevokeInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
